********************************************************************
*                                                                  *
*                     TEMPUS KEYBOARD CODES                        *
*                                                                  *
********************************************************************


      


cntrl-E     search string
cntrl-R     page UP
cntrl-C     page DOWN                            
cntrl-T     Delete RIGHT
cntrl-Y     Delete LINE
cntrl-U     replace Text from Disk
cntrl-I     tab
cntrl-P     print 
cntrl-A     word to left
cntrl-S     SAVE and resume
cntrl-D     jump to page..
cntrl-F     word to right
cntrl-K     mark block End
cntrl-L     search string
cntrl-Z     jump to Mark togle
cntrl-X     EXIT - QUIT! with save
cntrl-B     mark block START
cntrl-N     insert line


alt-Q     invert screen colours
alt-W     SAVE text As...
alt-E     jump to END of text
alt-R     merge text
alt-T     jump to TOP of text
alt-U     paging offset
alt-O     load font from disk
alt-S     SAVE and resume
alt-F     function key define
alt-J     save TEMPUS colours to disk
alt-Z     jump to line
alt-X     open text 
alt-V     statistics
alt-N     set new tab stops


